# Generated by Django 4.1 on 2022-09-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя категории')),
                ('description', models.TextField(max_length=2048, null=True, verbose_name='Описание')),
                ('label', models.CharField(max_length=255, verbose_name='Примечание')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('featured', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('slug', models.SlugField(unique=True, verbose_name='Путь')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32, verbose_name='Сессия')),
                ('customer_name', models.CharField(max_length=128, null=True, verbose_name='Имя покупателя')),
                ('customer_address', models.CharField(max_length=256, null=True, verbose_name='Адрес покупателя')),
                ('customer_phone', models.CharField(max_length=16, null=True, verbose_name='Телефон покупателя')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Общая цена')),
                ('finalized', models.BooleanField(default=False, verbose_name='Заказ завершён')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(max_length=2048, null=True, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Старая цена')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('sale', models.BooleanField(default=False, verbose_name='Распродажа')),
                ('featured', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('slug', models.SlugField(unique=True, verbose_name='Путь')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена на момент покупки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Продукт')),
            ],
        ),
    ]
